#!/usr/bin/env python3
"""
git-plan.py — Create a GitHub Project with Epics and Issues from an approved plan.

Usage:
    python3 git-plan.py --meta '<JSON>'
    python3 git-plan.py --meta '<JSON>' --project-number 5   # skip project creation

--meta is generated by Claude from the approved plan file and passed in as a JSON string.
Re-runs are safe: existing issues are detected by title and reused rather than duplicated.
Status is only assigned to newly created issues — existing items are never overwritten.
"""

import argparse
import json
import os
import subprocess
import sys

# Allow importing issue_utils from the same directory regardless of cwd.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from issue_utils import (  # noqa: E402
    run, run_silent,
    get_or_create_issue, issue_number_from_url, append_blocked_by,
    get_project_node_id, set_item_status,
)

BLUE  = "\033[34m"
RESET = "\033[0m"


# ── Pre-flight ────────────────────────────────────────────────────────────────

def check_auth_scopes():
    """Exit with a clear message if the gh token is missing the project scope."""
    result = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True)
    output = result.stdout + result.stderr
    scopes_line = next((l for l in output.splitlines() if "Token scopes" in l), "")
    if "project" not in scopes_line:
        print("ERROR: gh token is missing required scopes.")
        print("  Run in a terminal: gh auth refresh -s project,read:project")
        sys.exit(1)


# ── Project helpers ───────────────────────────────────────────────────────────

def create_or_find_project(owner, title, repo):
    """Create a GitHub Project, link it to repo, and return (number, url, node_id)."""
    result = subprocess.run(
        ["gh", "project", "create", "--owner", owner, "--title", title, "--format", "json"],
        capture_output=True, text=True
    )
    if result.returncode == 0 and result.stdout.strip():
        data    = json.loads(result.stdout)
        number  = data["number"]
        url     = data["url"]
        run(["gh", "project", "link", str(number), "--owner", owner, "--repo", repo],
            description=f"link project #{number} to {repo}")
        node_id = get_project_node_id(owner, number)
        return number, url, node_id

    list_out = run(["gh", "project", "list", "--owner", owner, "--format", "json"],
                   description="gh project list")
    for p in json.loads(list_out).get("projects", []):
        if p["title"] == title:
            print(f"  (project already exists — reusing #{p['number']})")
            node_id = get_project_node_id(owner, p["number"])
            return p["number"], p["url"], node_id

    print(f"ERROR: could not create or find project '{title}'")
    sys.exit(1)


# ── Status field helpers ──────────────────────────────────────────────────────

EXTRA_STATUSES = [
    {"name": "Backlog", "color": "GRAY",   "description": "Work that can be done but carries the least priority"},
    {"name": "Verify",  "color": "ORANGE", "description": "Code is delivered but requires validation to close"},
    {"name": "Ready",   "color": "BLUE",   "description": "Work that is not pending other tasks to be started"},
]


def configure_project_statuses(project_number, owner):
    """Add Backlog, Verify, and Ready to the project's Status field.

    Returns (field_id, {name: option_id}) for use when assigning status to new items,
    or (None, {}) if the Status field is not found.
    """
    query = """
query($login: String!, $number: Int!) {
  user(login: $login) {
    projectV2(number: $number) {
      fields(first: 20) {
        nodes {
          ... on ProjectV2SingleSelectField {
            id name
            options { id name color description }
          }
        }
      }
    }
  }
}"""
    out = run(["gh", "api", "graphql",
               "-f", f"query={query}",
               "-f", f"login={owner}",
               "-F", f"number={project_number}"],
              description="query project status field")
    nodes = json.loads(out)["data"]["user"]["projectV2"]["fields"]["nodes"]
    status = next((n for n in nodes if n.get("name") == "Status"), None)
    if not status:
        print("  WARNING: Status field not found — skipping")
        return None, {}

    field_id       = status["id"]
    existing_names = {o["name"] for o in status["options"]}
    all_options    = list(status["options"])
    to_add         = [s for s in EXTRA_STATUSES if s["name"] not in existing_names]

    if not to_add:
        print("  (status options already configured)")
        return field_id, {o["name"]: o["id"] for o in status["options"]}

    all_options += to_add
    opts_gql = " ".join(
        f'{{name: "{o["name"]}", color: {o["color"]}, description: "{o["description"]}"}}'
        for o in all_options
    )
    mutation = f"""
mutation {{
  updateProjectV2Field(input: {{
    fieldId: "{field_id}"
    singleSelectOptions: [{opts_gql}]
  }}) {{
    projectV2Field {{
      ... on ProjectV2SingleSelectField {{
        id
        options {{ id name }}
      }}
    }}
  }}
}}"""
    mut_out = run(["gh", "api", "graphql", "-f", f"query={mutation}"],
                  description="update project status options")
    print(f"  Added: {', '.join(s['name'] for s in to_add)}")

    # The mutation returns fresh option IDs — build the full name→id map.
    updated_opts = (json.loads(mut_out)["data"]["updateProjectV2Field"]
                    ["projectV2Field"]["options"])
    return field_id, {o["name"]: o["id"] for o in updated_opts}


# ── Issue helpers ─────────────────────────────────────────────────────────────

def load_existing_issues(repo):
    """Fetch all issues (open and closed) and return a title → {number, url} dict.

    Includes closed issues so re-runs don't recreate completed work.
    """
    out, ok = run_silent(["gh", "issue", "list", "--repo", repo,
                          "--state", "all", "--json", "number,title,url", "--limit", "500"])
    if not ok or not out:
        return {}
    return {i["title"]: {"number": i["number"], "url": i["url"]} for i in json.loads(out)}


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Create a GitHub Project, Epics, and Issues from an approved plan"
    )
    parser.add_argument(
        "--meta", required=True,
        help='JSON: {"project_title": "...", "repo": "OWNER/REPO", "epics": [...]}'
    )
    parser.add_argument(
        "--project-number", type=int, default=None,
        help="Skip project creation and use this existing project number"
    )
    args = parser.parse_args()

    # Pre-flight
    check_auth_scopes()

    try:
        meta          = json.loads(args.meta)
        project_title = meta["project_title"]
        repo          = meta["repo"]
        epics         = meta["epics"]
    except (json.JSONDecodeError, KeyError) as exc:
        print(f"ERROR: --meta is invalid — {exc}")
        print('  Expected: {"project_title": "...", "repo": "OWNER/REPO", "epics": [...]}')
        sys.exit(1)

    owner        = repo.split("/")[0]
    total_issues = sum(len(e["issues"]) for e in epics)

    print(f"Repo:    {repo}")
    print(f"Project: {project_title}")
    print(f"Epics:   {len(epics)}")
    print(f"Issues:  {total_issues}")
    print()

    # ── Step 1: Project ───────────────────────────────────────────────────────
    print("GitHub Project...")
    if args.project_number:
        project_number = args.project_number
        project_url    = f"https://github.com/users/{owner}/projects/{project_number}"
        project_id     = get_project_node_id(owner, project_number)
        print(f"  (skipping — using existing #{project_number})")
    else:
        project_number, project_url, project_id = create_or_find_project(owner, project_title, repo)
    print(f"{BLUE}→ Project #{project_number}: {project_url}{RESET}")

    print("Configuring status options...")
    status_field_id, status_options = configure_project_statuses(project_number, owner)
    print()

    # ── Load existing issues once ─────────────────────────────────────────────
    print("Loading existing issues...")
    existing = load_existing_issues(repo)
    print(f"  {len(existing)} issues found (open + closed)\n")

    # ── Step 2: Epics (placeholder checklists) ────────────────────────────────
    print("Epics...")
    epic_records = []
    for epic in epics:
        placeholder = "\n".join(f"- [ ] {i['title']}" for i in epic["issues"])
        if epic.get("description"):
            placeholder = epic["description"] + "\n\n" + placeholder

        number, url, created = get_or_create_issue(
            repo, epic["title"], placeholder, ["Epic"], existing
        )
        create_status = "created" if created else "exists"
        epic_records.append({
            "epic": epic, "number": number, "url": url,
            "status": epic.get("status", "Todo"),
            "created": created,
            "children": [],
        })
        print(f"  #{number} [{create_status}]: {epic['title']}")

    print()

    # ── Step 3: Child issues ──────────────────────────────────────────────────
    print("Issues...")
    for record in epic_records:
        for issue in record["epic"]["issues"]:
            number, url, created = get_or_create_issue(
                repo,
                issue["title"],
                issue.get("description", ""),
                issue.get("labels", []),
                existing,
            )
            create_status = "created" if created else "exists"
            record["children"].append({
                "number": number, "url": url, "title": issue["title"],
                "status":     issue.get("status", "Ready"),
                "blocked_by": issue.get("blocked_by", []),
                "created":    created,
                "body":       issue.get("description", ""),
            })
            print(f"  #{number} [{create_status}]: {issue['title']}")

    print()

    # ── Step 3.5: Write Blocked By sections ───────────────────────────────────
    blocked_items = [
        child for record in epic_records
        for child in record["children"]
        if child["blocked_by"] and child["created"]
    ]
    if blocked_items:
        print("Writing dependency links...")
        for child in blocked_items:
            resolved = []
            for blocker_title in child["blocked_by"]:
                entry = existing.get(blocker_title)
                if entry:
                    resolved.append((entry["number"], blocker_title))
                else:
                    print(f"  WARNING: blocker '{blocker_title}' not found — skipping")
            if resolved:
                append_blocked_by(repo, child["number"], child["body"], resolved)
                refs = ", ".join(f"#{n}" for n, _ in resolved)
                print(f"  #{child['number']} blocked by {refs}")
        print()

    # ── Step 4: Link issues back into Epic checklists ─────────────────────────
    # Only rewrite epic bodies for newly created epics. Existing epics may have
    # been manually edited and the checklist is already linked from a prior run.
    print("Linking issues into Epic checklists...")
    for record in epic_records:
        if not record["created"]:
            print(f"  Epic #{record['number']} [exists] — skipping body rewrite")
            continue
        linked = "\n".join(f"- [ ] #{c['number']} {c['title']}" for c in record["children"])
        if record["epic"].get("description"):
            linked = record["epic"]["description"] + "\n\n" + linked

        run(["gh", "issue", "edit", str(record["number"]),
             "--repo", repo,
             "--body", linked],
            description=f"link epic #{record['number']}")
        print(f"  Epic #{record['number']} → {len(record['children'])} issues linked")

    print()

    # ── Step 5: Add all items to project; set status only for new items ───────
    print("Adding items to project...")
    all_items = (
        [{"url": r["url"], "status": r["status"], "created": r["created"]} for r in epic_records] +
        [{"url": c["url"], "status": c["status"], "created": c["created"]}
         for r in epic_records for c in r["children"]]
    )
    added = skipped = 0
    for item in all_items:
        out, ok = run_silent(["gh", "project", "item-add", str(project_number),
                              "--owner", owner, "--url", item["url"], "--format", "json"])
        if ok:
            added += 1
            if item["created"] and status_field_id and status_options and out:
                item_id   = json.loads(out).get("id")
                option_id = status_options.get(item["status"])
                if item_id and option_id:
                    set_item_status(project_id, item_id, status_field_id, option_id)
        else:
            skipped += 1

    print(f"{BLUE}→ {added} items added, {skipped} already in project{RESET}\n")
    print(f"Done.  {project_url}")


if __name__ == "__main__":
    main()
