#!/usr/bin/env python3
"""
git-plan.py — Create a GitHub Project with Epics and Issues from an approved plan.

Usage:
    python3 git-plan.py --meta '<JSON>'
    python3 git-plan.py --meta '<JSON>' --project-number 5   # skip project creation

--meta is generated by Claude from the approved plan file and passed in as a JSON string.
Re-runs are safe: existing issues are detected by title and reused rather than duplicated.
Status is only assigned to newly created issues — existing items are never overwritten.
"""

import argparse
import json
import os
import sys

# Allow importing siblings regardless of cwd.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import github_client  # noqa: E402
from issue_utils import (  # noqa: E402
    get_or_create_issue, append_blocked_by,
    get_project_node_id, set_item_status,
    find_active_project,
)

BLUE  = "\033[34m"
RESET = "\033[0m"


# ── Pre-flight ────────────────────────────────────────────────────────────────

def check_auth():
    """Verify the token is valid and warn if project scope can't be confirmed."""
    scopes = github_client.token_scopes()
    if scopes and "project" not in scopes:
        print("ERROR: GitHub token is missing the 'project' scope.")
        print("  Run: python3 github_client.py --set-token")
        sys.exit(1)
    if not scopes:
        # Fine-grained PAT — scopes not advertised; permission errors surface at call time.
        pass


# ── Project helpers ───────────────────────────────────────────────────────────

def _get_owner_node_id(owner):
    q = """query($login: String!) { user(login: $login) { id } }"""
    return github_client.graphql(q, {"login": owner})["data"]["user"]["id"]


def create_or_find_project(owner, title, repo):
    """Create a GitHub Project V2, link it to repo, and return (number, url, node_id).

    Checks for an existing project with the same title first to make re-runs safe.
    """
    # Check for existing project
    list_q = """
query($login: String!, $first: Int!) {
  user(login: $login) {
    projectsV2(first: $first) {
      nodes { id number title url }
    }
  }
}"""
    data = github_client.graphql(list_q, {"login": owner, "first": 50})
    for p in data["data"]["user"]["projectsV2"]["nodes"]:
        if p["title"] == title:
            print(f"  (project already exists — reusing #{p['number']})")
            return p["number"], p["url"], p["id"]

    # Create new project
    owner_id = _get_owner_node_id(owner)
    create_m = """
mutation($ownerId: ID!, $title: String!) {
  createProjectV2(input: {ownerId: $ownerId, title: $title}) {
    projectV2 { id number url }
  }
}"""
    project = github_client.graphql(create_m, {"ownerId": owner_id, "title": title})
    project = project["data"]["createProjectV2"]["projectV2"]

    # Link to repo
    repo_data   = github_client.rest("GET", f"/repos/{repo}")
    repo_nid    = repo_data["node_id"]
    link_m = """
mutation($projectId: ID!, $repositoryId: ID!) {
  linkProjectV2ToRepository(input: {projectId: $projectId, repositoryId: $repositoryId}) {
    repository { id }
  }
}"""
    github_client.graphql(link_m, {"projectId": project["id"], "repositoryId": repo_nid})

    return project["number"], project["url"], project["id"]


# ── Status field helpers ──────────────────────────────────────────────────────

EXTRA_STATUSES = [
    {"name": "Backlog", "color": "GRAY",   "description": "Work that can be done but carries the least priority"},
    {"name": "Verify",  "color": "ORANGE", "description": "Code is delivered but requires validation to close"},
    {"name": "Ready",   "color": "BLUE",   "description": "Work that is not pending other tasks to be started"},
]


def configure_project_statuses(project_number, owner):
    """Add Backlog, Verify, and Ready to the project's Status field.

    Returns (field_id, {name: option_id}) for use when assigning status to new items,
    or (None, {}) if the Status field is not found.
    """
    query = """
query($login: String!, $number: Int!) {
  user(login: $login) {
    projectV2(number: $number) {
      fields(first: 20) {
        nodes {
          ... on ProjectV2SingleSelectField {
            id name
            options { id name color description }
          }
        }
      }
    }
  }
}"""
    data  = github_client.graphql(query, {"login": owner, "number": project_number})
    nodes = data["data"]["user"]["projectV2"]["fields"]["nodes"]
    status = next((n for n in nodes if n.get("name") == "Status"), None)
    if not status:
        print("  WARNING: Status field not found — skipping")
        return None, {}

    field_id       = status["id"]
    existing_names = {o["name"] for o in status["options"]}
    to_add         = [s for s in EXTRA_STATUSES if s["name"] not in existing_names]

    if not to_add:
        print("  (status options already configured)")
        return field_id, {o["name"]: o["id"] for o in status["options"]}

    all_options = [
        {"name": o["name"], "color": o["color"], "description": o.get("description", "")}
        for o in status["options"]
    ] + to_add

    mutation = """
mutation($fieldId: ID!, $options: [ProjectV2SingleSelectFieldOptionInput!]!) {
  updateProjectV2Field(input: {
    fieldId: $fieldId
    singleSelectOptions: $options
  }) {
    projectV2Field {
      ... on ProjectV2SingleSelectField {
        id
        options { id name }
      }
    }
  }
}"""
    mut_data = github_client.graphql(mutation, {"fieldId": field_id, "options": all_options})
    print(f"  Added: {', '.join(s['name'] for s in to_add)}")

    updated_opts = mut_data["data"]["updateProjectV2Field"]["projectV2Field"]["options"]
    return field_id, {o["name"]: o["id"] for o in updated_opts}


# ── Issue helpers ─────────────────────────────────────────────────────────────

def load_existing_issues(repo):
    """Fetch all issues (open and closed) and return a title → {number, url, node_id} dict.

    Includes closed issues so re-runs don't recreate completed work.
    """
    result = {}
    page   = 1
    while True:
        issues = github_client.rest("GET", f"/repos/{repo}/issues",
                                    params={"state": "all", "per_page": 100, "page": page})
        if not issues:
            break
        for issue in issues:
            if "pull_request" in issue:
                continue
            result[issue["title"]] = {
                "number":  issue["number"],
                "url":     issue["html_url"],
                "node_id": issue["node_id"],
            }
        if len(issues) < 100:
            break
        page += 1
    return result


# ── Project item helpers ──────────────────────────────────────────────────────

def add_item_to_project(project_id, content_node_id):
    """Add an issue to a project V2. Idempotent — returns item ID whether new or existing."""
    mutation = """
mutation($projectId: ID!, $contentId: ID!) {
  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
    item { id }
  }
}"""
    data = github_client.graphql(mutation, {
        "projectId": project_id,
        "contentId": content_node_id,
    })
    return data["data"]["addProjectV2ItemById"]["item"]["id"]


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Create a GitHub Project, Epics, and Issues from an approved plan"
    )
    parser.add_argument(
        "--meta", required=True,
        help='JSON: {"project_title": "...", "repo": "OWNER/REPO", "epics": [...]}'
    )
    parser.add_argument(
        "--project-number", type=int, default=None,
        help="Skip project creation and use this existing project number"
    )
    args = parser.parse_args()

    check_auth()

    try:
        meta          = json.loads(args.meta)
        project_title = meta["project_title"]
        repo          = meta["repo"]
        epics         = meta["epics"]
    except (json.JSONDecodeError, KeyError) as exc:
        print(f"ERROR: --meta is invalid — {exc}")
        print('  Expected: {"project_title": "...", "repo": "OWNER/REPO", "epics": [...]}')
        sys.exit(1)

    owner        = repo.split("/")[0]

    # ── Active-project guard ──────────────────────────────────────────────────
    if not args.project_number:
        active = find_active_project(owner)
        if active:
            print(f"ERROR: An active project already has open issues.")
            print(f"  #{active['number']}: {active['title']}")
            print(f"  {active['url']}")
            print()
            print("Resolve or close existing issues before creating a new project.")
            print("To advance newly-unblocked items to Ready, run:")
            print("  python3 project_items.py --advance-ready")
            sys.exit(1)
    total_issues = sum(len(e["issues"]) for e in epics)

    print(f"Repo:    {repo}")
    print(f"Project: {project_title}")
    print(f"Epics:   {len(epics)}")
    print(f"Issues:  {total_issues}")
    print()

    # ── Step 1: Project ───────────────────────────────────────────────────────
    print("GitHub Project...")
    if args.project_number:
        project_number = args.project_number
        project_url    = f"https://github.com/users/{owner}/projects/{project_number}"
        project_id     = get_project_node_id(owner, project_number)
        print(f"  (skipping — using existing #{project_number})")
    else:
        project_number, project_url, project_id = create_or_find_project(owner, project_title, repo)
    print(f"{BLUE}→ Project #{project_number}: {project_url}{RESET}")

    print("Configuring status options...")
    status_field_id, status_options = configure_project_statuses(project_number, owner)
    print()

    # ── Load existing issues once ─────────────────────────────────────────────
    print("Loading existing issues...")
    existing = load_existing_issues(repo)
    print(f"  {len(existing)} issues found (open + closed)\n")

    # ── Step 2: Epics (placeholder checklists) ────────────────────────────────
    print("Epics...")
    epic_records = []
    for epic in epics:
        placeholder = "\n".join(f"- [ ] {i['title']}" for i in epic["issues"])
        if epic.get("description"):
            placeholder = epic["description"] + "\n\n" + placeholder

        number, url, node_id, created = get_or_create_issue(
            repo, epic["title"], placeholder, ["Epic"], existing
        )
        create_status = "created" if created else "exists"
        epic_records.append({
            "epic":    epic, "number": number, "url": url, "node_id": node_id,
            "status":  epic.get("status", "Todo"),
            "created": created,
            "children": [],
        })
        print(f"  #{number} [{create_status}]: {epic['title']}")

    print()

    # ── Step 3: Child issues ──────────────────────────────────────────────────
    print("Issues...")
    for record in epic_records:
        for issue in record["epic"]["issues"]:
            number, url, node_id, created = get_or_create_issue(
                repo,
                issue["title"],
                issue.get("description", ""),
                issue.get("labels", []),
                existing,
            )
            create_status = "created" if created else "exists"
            record["children"].append({
                "number":     number,
                "url":        url,
                "node_id":    node_id,
                "title":      issue["title"],
                "status":     issue.get("status", "Ready"),
                "blocked_by": issue.get("blocked_by", []),
                "created":    created,
                "body":       issue.get("description", ""),
            })
            print(f"  #{number} [{create_status}]: {issue['title']}")

    print()

    # ── Step 3.5: Write Blocked By sections ───────────────────────────────────
    blocked_items = [
        child for record in epic_records
        for child in record["children"]
        if child["blocked_by"] and child["created"]
    ]
    if blocked_items:
        print("Writing dependency links...")
        for child in blocked_items:
            resolved = []
            for blocker_title in child["blocked_by"]:
                entry = existing.get(blocker_title)
                if entry:
                    resolved.append((entry["number"], blocker_title))
                else:
                    print(f"  WARNING: blocker '{blocker_title}' not found — skipping")
            if resolved:
                append_blocked_by(repo, child["number"], child["body"], resolved)
                refs = ", ".join(f"#{n}" for n, _ in resolved)
                print(f"  #{child['number']} blocked by {refs}")
        print()

    # ── Step 4: Link issues back into Epic checklists ─────────────────────────
    # Only rewrite epic bodies for newly created epics. Existing epics may have
    # been manually edited and the checklist is already linked from a prior run.
    print("Linking issues into Epic checklists...")
    for record in epic_records:
        if not record["created"]:
            print(f"  Epic #{record['number']} [exists] — skipping body rewrite")
            continue
        linked = "\n".join(f"- [ ] #{c['number']} {c['title']}" for c in record["children"])
        if record["epic"].get("description"):
            linked = record["epic"]["description"] + "\n\n" + linked

        github_client.rest("PATCH", f"/repos/{repo}/issues/{record['number']}",
                           json={"body": linked})
        print(f"  Epic #{record['number']} → {len(record['children'])} issues linked")

    print()

    # ── Step 5: Add all items to project; set status only for new items ───────
    print("Adding items to project...")
    all_items = (
        [{"node_id": r["node_id"], "status": r["status"], "created": r["created"]}
         for r in epic_records] +
        [{"node_id": c["node_id"], "status": c["status"], "created": c["created"]}
         for r in epic_records for c in r["children"]]
    )
    for item in all_items:
        item_id   = add_item_to_project(project_id, item["node_id"])
        if item["created"] and status_field_id and status_options:
            option_id = status_options.get(item["status"])
            if option_id:
                set_item_status(project_id, item_id, status_field_id, option_id)

    print(f"{BLUE}→ {len(all_items)} items added to project{RESET}\n")
    print(f"Done.  {project_url}")


if __name__ == "__main__":
    main()
