#!/usr/bin/env python3
"""
pr.py — Create a pull request for a git repo with uncommitted changes.

Usage:
    python3 pr.py --meta '{"branch_name": "...", "commit_message": "...", "pr_title": "...", "pr_body": "..."}' [--repo REPO_PATH]

--meta is generated by Claude in-conversation and passed in as a JSON string.
--repo defaults to the current working directory if omitted.
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

CO_AUTHOR = "Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
BLUE = "\033[34m"
RESET = "\033[0m"


# ---------------------------------------------------------------------------
# Shell helpers — errors are always explicit and labelled for Claude to parse
# ---------------------------------------------------------------------------

def run(args, cwd=None):
    """Run a command (list or string), return stdout. Exit with a clear error on failure."""
    if isinstance(args, str):
        args = ["bash", "-c", args]
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        cmd_str = " ".join(args) if isinstance(args, list) else args
        print(f"\nERROR: command failed (exit {result.returncode})")
        print(f"  CMD:    {cmd_str}")
        if result.stdout.strip():
            print(f"  STDOUT: {result.stdout.strip()}")
        if result.stderr.strip():
            print(f"  STDERR: {result.stderr.strip()}")
        sys.exit(1)
    return result.stdout.strip()


def run_silent(args, cwd=None):
    """Run a command; return (stdout, ok) without raising."""
    if isinstance(args, str):
        args = ["bash", "-c", args]
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    return result.stdout.strip(), result.returncode == 0


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def find_base_branch(repo):
    remote_branches, _ = run_silent(["git", "branch", "-r"], cwd=repo)
    if "origin/main" in remote_branches:
        return "main"
    if "origin/develop" in remote_branches:
        return "develop"
    return None


def is_behind_origin(repo, base):
    status = run(["git", "status", "-uno"], cwd=repo)
    return "behind" in status


def has_changes(repo, base):
    diff_stat = run(["git", "diff", f"origin/{base}", "--stat"], cwd=repo)
    status = run(["git", "status", "--short"], cwd=repo)
    return bool(diff_stat or status), diff_stat, status


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Open a PR for uncommitted changes")
    parser.add_argument("--repo", default=os.getcwd(), help="Path to git repo (default: cwd)")
    parser.add_argument("--meta", required=True, help='JSON string: {"branch_name","commit_message","pr_title","pr_body"}')
    args = parser.parse_args()
    repo = str(Path(args.repo).resolve())

    # Parse metadata from Claude
    try:
        meta = json.loads(args.meta)
        branch_name    = meta["branch_name"]
        commit_message = meta["commit_message"]
        pr_title       = meta["pr_title"]
        pr_body        = meta["pr_body"]
        labels         = meta.get("labels", [])
    except (json.JSONDecodeError, KeyError) as exc:
        print(f"ERROR: --meta is invalid — {exc}")
        print(f"  Expected: {{\"branch_name\": \"...\", \"commit_message\": \"...\", \"pr_title\": \"...\", \"pr_body\": \"...\", \"labels\": [...]}}")
        print(f"  Got: {args.meta}")
        sys.exit(1)

    # Validate repo
    _, ok = run_silent("git rev-parse --git-dir", cwd=repo)
    if not ok:
        print(f"ERROR: Not a git repository: {repo}")
        sys.exit(1)

    print(f"Repo: {repo}")

    # Fetch + base branch
    print("Fetching from origin...")
    run(["git", "fetch", "origin"], cwd=repo)

    base = find_base_branch(repo)
    if not base:
        print("ERROR: origin has neither 'main' nor 'develop' — cannot determine base branch.")
        sys.exit(1)
    print(f"Base: {base}")

    # Check for changes
    changed, diff_stat, status = has_changes(repo, base)
    if not changed:
        print(f"Nothing to PR — working tree matches origin/{base}.")
        sys.exit(0)

    # Current branch + sync state
    current_branch = run(["git", "branch", "--show-current"], cwd=repo)
    already_on_base = current_branch == base
    behind = is_behind_origin(repo, base)

    print(f"  branch:  {branch_name}")
    print(f"  commit:  {commit_message}")

    # Stash / sync only when necessary
    stashed = False
    if not already_on_base or behind:
        reason = "not on base branch" if not already_on_base else "local is behind origin"
        print(f"Stashing ({reason})...")
        run(["git", "stash", "push", "-u", "-m", "pr-script-stash"], cwd=repo)
        stashed = True
        run(["git", "checkout", base], cwd=repo)
        run(["git", "pull", "origin", base], cwd=repo)
    else:
        print("Already on base and up to date — skipping stash/pull.")

    # Create branch
    run_silent(["git", "branch", "-D", branch_name], cwd=repo)  # delete stale, ignore failure
    run(["git", "checkout", "-b", branch_name], cwd=repo)

    if stashed:
        run(["git", "stash", "pop"], cwd=repo)

    transition = (
        f"{current_branch} → {base} → {branch_name}"
        if stashed
        else f"{current_branch} → {branch_name}"
    )
    print(f"{BLUE}→ {Path(repo).name}: {transition}{RESET}")

    # Commit + push
    run(["git", "add", "-A"], cwd=repo)
    run(["git", "commit", "-m", commit_message, "-m", CO_AUTHOR], cwd=repo)
    run(["git", "push", "-u", "origin", branch_name], cwd=repo)
    print(f"{BLUE}→ Publishing {branch_name} to origin{RESET}")

    # PR
    gh_repo = run(["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"], cwd=repo)
    pr_url = run(
        ["gh", "pr", "create",
         "--repo", gh_repo,
         "--base", base,
         "--head", branch_name,
         "--title", pr_title,
         "--body", pr_body],
        cwd=repo,
    )
    print(f"\nPR: {pr_url}")

    # Apply labels
    if labels:
        pr_number = pr_url.rstrip("/").split("/")[-1]
        run(["gh", "pr", "edit", pr_number, "--repo", gh_repo, "--add-label", ",".join(labels)], cwd=repo)
        print(f"Labels: {', '.join(labels)}")

    # PR list
    prs_raw = run(
        ["gh", "pr", "list", "--repo", gh_repo, "--state", "open",
         "--json", "number,title,headRefName,createdAt,url"],
        cwd=repo,
    )
    prs = sorted(json.loads(prs_raw), key=lambda p: p["createdAt"])[:3]
    total = run(["gh", "pr", "list", "--repo", gh_repo, "--state", "open", "--json", "number"], cwd=repo)
    total_count = len(json.loads(total))
    print(f"\nOpen PRs ({total_count} total):")
    for i, pr in enumerate(prs, 1):
        date = pr["createdAt"][:10]
        entry = f"  {i}. #{pr['number']} — {pr['title']} ({pr['headRefName']}) — {date}"
        if pr["url"] == pr_url:
            print(f"{BLUE}{entry}{RESET}")
        else:
            print(entry)


if __name__ == "__main__":
    main()
