#!/usr/bin/env python3
"""
pr.py — Create a pull request for a git repo.

Handles both shapes of input:
  * uncommitted changes  -> stash if needed, branch off a fresh base, commit, push, open the PR
  * a branch already ahead of base -> push it as-is and open the PR from it

The second case used to destroy the work it was given: the script force-deleted the branch holding
the commits and rebuilt it from base, reporting only a confusing failure about a stash. It now never
re-creates a branch that carries commits (see delete_branch_safely).

Usage:
    python3 pr.py --meta '{"branch_name": "...", "commit_message": "...", "pr_title": "...", "pr_body": "..."}' [--repo REPO_PATH]

branch_name and commit_message are only used when this script CREATES the branch and commit. If the
current branch is already ahead of base, its existing name and commits are used unchanged.

--meta is generated by Claude in-conversation and passed in as a JSON string.
--repo defaults to the current working directory if omitted.
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

CO_AUTHOR = "Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
BLUE = "\033[34m"
RESET = "\033[0m"


# ---------------------------------------------------------------------------
# Shell helpers — errors are always explicit and labelled for Claude to parse
# ---------------------------------------------------------------------------

def run(args, cwd=None):
    """Run a command (list or string), return stdout. Exit with a clear error on failure."""
    if isinstance(args, str):
        args = ["bash", "-c", args]
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        cmd_str = " ".join(args) if isinstance(args, list) else args
        print(f"\nERROR: command failed (exit {result.returncode})")
        print(f"  CMD:    {cmd_str}")
        if result.stdout.strip():
            print(f"  STDOUT: {result.stdout.strip()}")
        if result.stderr.strip():
            print(f"  STDERR: {result.stderr.strip()}")
        sys.exit(1)
    return result.stdout.strip()


def run_silent(args, cwd=None):
    """Run a command; return (stdout, ok) without raising."""
    if isinstance(args, str):
        args = ["bash", "-c", args]
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    return result.stdout.strip(), result.returncode == 0


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def find_base_branch(repo):
    remote_branches, _ = run_silent(["git", "branch", "-r"], cwd=repo)
    if "origin/main" in remote_branches:
        return "main"
    if "origin/develop" in remote_branches:
        return "develop"
    return None


def is_behind_origin(repo, base):
    status = run(["git", "status", "-uno"], cwd=repo)
    return "behind" in status


def has_changes(repo, base):
    diff_stat = run(["git", "diff", f"origin/{base}", "--stat"], cwd=repo)
    status = run(["git", "status", "--short"], cwd=repo)
    return bool(diff_stat or status), diff_stat, status


def commits_ahead(repo, base, ref="HEAD"):
    """How many commits `ref` carries that origin/<base> does not."""
    out, ok = run_silent(["git", "rev-list", "--count", f"origin/{base}..{ref}"], cwd=repo)
    return int(out) if ok and out.isdigit() else 0


def working_tree_dirty(repo):
    return bool(run(["git", "status", "--porcelain"], cwd=repo))


def delete_branch_safely(repo, branch, base):
    """Delete a stale local branch — but never one that is holding commits.

    `git branch -D` is unconditional: it will drop a branch whose commits exist nowhere else, and
    say nothing about it. That is how this script used to destroy already-committed work — it
    force-deleted the very branch it had been asked to open a PR from, then rebuilt it from base.
    A branch with commits the base does not have is not "stale", it is the thing we are here for.
    """
    exists, _ = run_silent(["git", "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"], cwd=repo)
    if not exists:
        return
    ahead = commits_ahead(repo, base, branch)
    if ahead:
        print(f"\nERROR: refusing to delete branch '{branch}' — it holds {ahead} commit(s) not on {base}.")
        print("  Those commits would be unrecoverable except via the reflog.")
        print(f"  If they are the work you want to PR, check the branch out and rerun; if they are")
        print(f"  genuinely stale, delete it yourself: git branch -D {branch}")
        sys.exit(1)
    run_silent(["git", "branch", "-D", branch], cwd=repo)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Open a PR for a git repo (committed or uncommitted work)")
    parser.add_argument("--repo", default=os.getcwd(), help="Path to git repo (default: cwd)")
    parser.add_argument("--meta", required=True, help='JSON string: {"branch_name","commit_message","pr_title","pr_body"}')
    args = parser.parse_args()
    repo = str(Path(args.repo).resolve())

    # Parse metadata from Claude
    try:
        meta = json.loads(args.meta)
        branch_name    = meta["branch_name"]
        commit_message = meta["commit_message"]
        pr_title       = meta["pr_title"]
        pr_body        = meta["pr_body"]
        labels         = meta.get("labels", [])
    except (json.JSONDecodeError, KeyError) as exc:
        print(f"ERROR: --meta is invalid — {exc}")
        print(f"  Expected: {{\"branch_name\": \"...\", \"commit_message\": \"...\", \"pr_title\": \"...\", \"pr_body\": \"...\", \"labels\": [...]}}")
        print(f"  Got: {args.meta}")
        sys.exit(1)

    # Validate repo
    _, ok = run_silent("git rev-parse --git-dir", cwd=repo)
    if not ok:
        print(f"ERROR: Not a git repository: {repo}")
        sys.exit(1)

    print(f"Repo: {repo}")

    # Fetch + base branch
    print("Fetching from origin...")
    run(["git", "fetch", "origin"], cwd=repo)

    base = find_base_branch(repo)
    if not base:
        print("ERROR: origin has neither 'main' nor 'develop' — cannot determine base branch.")
        sys.exit(1)
    print(f"Base: {base}")

    # Check for changes
    changed, diff_stat, status = has_changes(repo, base)
    if not changed:
        print(f"Nothing to PR — working tree matches origin/{base}.")
        sys.exit(0)

    # Current branch + sync state
    current_branch = run(["git", "branch", "--show-current"], cwd=repo)
    already_on_base = current_branch == base
    behind = is_behind_origin(repo, base)
    ahead = commits_ahead(repo, base)

    print(f"  branch:  {branch_name}")
    print(f"  commit:  {commit_message}")

    # -----------------------------------------------------------------------------------------
    # Two paths, and picking the wrong one loses work.
    #
    # The script was written for ONE of them: uncommitted changes, which it stashes, branches, and
    # commits for you. But committing before opening a PR is a perfectly normal thing to do — it is
    # what a reviewable series of focused commits requires — and on that input the old flow
    # force-deleted the branch holding those commits and rebuilt it from base. Silently.
    #
    # So: if the current branch is already ahead of the base, the commits ARE the contribution.
    # Push what exists and open the PR from it. Never re-create the branch.
    # -----------------------------------------------------------------------------------------
    if ahead and not already_on_base:
        head = current_branch
        if head != branch_name:
            # The caller's suggested name is only used when this script creates the branch. It did
            # not; renaming an existing branch under the caller would be a surprise of its own.
            print(f"Branch '{head}' already carries {ahead} commit(s) — opening the PR from it.")
            print(f"  (ignoring the suggested name '{branch_name}': the branch already exists)")
        else:
            print(f"Branch '{head}' already carries {ahead} commit(s) — opening the PR from it.")

        if working_tree_dirty(repo):
            print("Committing the remaining working-tree changes on top...")
            run(["git", "add", "-A"], cwd=repo)
            run(["git", "commit", "-m", commit_message, "-m", CO_AUTHOR], cwd=repo)

        run(["git", "push", "-u", "origin", head], cwd=repo)
        print(f"{BLUE}→ Publishing {head} to origin{RESET}")
        branch_name = head

    else:
        # Uncommitted changes: stash if we have to move, branch off a fresh base, commit.
        if ahead and already_on_base:
            print(f"\nERROR: {ahead} commit(s) sit on {base} itself — they cannot be PR'd from there.")
            print(f"  Move them to a branch first:  git branch {branch_name} && "
                  f"git reset --hard origin/{base}")
            sys.exit(1)

        stashed = False
        if not already_on_base or behind:
            reason = "not on base branch" if not already_on_base else "local is behind origin"
            print(f"Stashing ({reason})...")
            # Only claim to have stashed if a stash was actually created — a clean tree produces
            # "No local changes to save" and no entry, and the old code's unconditional `stash pop`
            # then failed with a message about a stash while the real damage was elsewhere.
            before, _ = run_silent(["git", "stash", "list"], cwd=repo)
            run(["git", "stash", "push", "-u", "-m", "pr-script-stash"], cwd=repo)
            after, _ = run_silent(["git", "stash", "list"], cwd=repo)
            stashed = after != before
            run(["git", "checkout", base], cwd=repo)
            run(["git", "pull", "origin", base], cwd=repo)
        else:
            print("Already on base and up to date — skipping stash/pull.")

        # Create branch. delete_branch_safely refuses to drop one that is holding commits.
        delete_branch_safely(repo, branch_name, base)
        run(["git", "checkout", "-b", branch_name], cwd=repo)

        if stashed:
            run(["git", "stash", "pop"], cwd=repo)

        transition = (
            f"{current_branch} → {base} → {branch_name}"
            if stashed
            else f"{current_branch} → {branch_name}"
        )
        print(f"{BLUE}→ {Path(repo).name}: {transition}{RESET}")

        # Commit + push
        run(["git", "add", "-A"], cwd=repo)
        run(["git", "commit", "-m", commit_message, "-m", CO_AUTHOR], cwd=repo)
        run(["git", "push", "-u", "origin", branch_name], cwd=repo)
        print(f"{BLUE}→ Publishing {branch_name} to origin{RESET}")

    # PR
    gh_repo = run(["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"], cwd=repo)
    pr_url = run(
        ["gh", "pr", "create",
         "--repo", gh_repo,
         "--base", base,
         "--head", branch_name,
         "--title", pr_title,
         "--body", pr_body],
        cwd=repo,
    )
    print(f"\nPR: {pr_url}")

    # Apply labels — auto-init defaults on remote if any are missing
    if labels:
        pr_number = pr_url.rstrip("/").split("/")[-1]
        label_result = subprocess.run(
            ["gh", "pr", "edit", pr_number, "--repo", gh_repo, "--add-label", ",".join(labels)],
            cwd=repo, capture_output=True, text=True,
        )
        if label_result.returncode != 0:
            if "not found" in label_result.stderr:
                print("Labels missing on remote — initializing defaults...")
                init_script = str(Path(__file__).parent / "init_labels.py")
                run([sys.executable, init_script, "--repo", gh_repo], cwd=repo)
                run(["gh", "pr", "edit", pr_number, "--repo", gh_repo, "--add-label", ",".join(labels)], cwd=repo)
            else:
                print(f"\nERROR: command failed (exit {label_result.returncode})")
                print(f"  CMD:    gh pr edit {pr_number} --repo {gh_repo} --add-label {','.join(labels)}")
                if label_result.stderr.strip():
                    print(f"  STDERR: {label_result.stderr.strip()}")
                sys.exit(1)
        print(f"Labels: {', '.join(labels)}")

    # PR list
    prs_raw = run(
        ["gh", "pr", "list", "--repo", gh_repo, "--state", "open",
         "--json", "number,title,headRefName,createdAt,url"],
        cwd=repo,
    )
    prs = sorted(json.loads(prs_raw), key=lambda p: p["createdAt"])[:3]
    total = run(["gh", "pr", "list", "--repo", gh_repo, "--state", "open", "--json", "number"], cwd=repo)
    total_count = len(json.loads(total))
    print(f"\nOpen PRs ({total_count} total):")
    for i, pr in enumerate(prs, 1):
        date = pr["createdAt"][:10]
        entry = f"  {i}. #{pr['number']} — {pr['title']} ({pr['headRefName']}) — {date}"
        if pr["url"] == pr_url:
            print(f"{BLUE}{entry}{RESET}")
        else:
            print(entry)


if __name__ == "__main__":
    main()
